#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Motor,  port1,           FL_DRIVE,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           BL_DRIVE,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           FR_DRIVE,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           BR_DRIVE,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

#include "./lib/SmartMotorLib.c"


void pre_auton() {
  SmartMotorsInit();
  SmartMotorRun();

  bStopTasksBetweenModes = true;
}

task autonomous() {


  AutonomousCodePlaceholderForTesting();
}


task usercontrol() {


  while (true) {


    UserControlCodePlaceholderForTesting();
  }
}
