#pragma config(Motor,  port1,          LIFT_CLAW,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,          LB_DRIVE,      tmotorVex393_MC29,    openLoop)
#pragma config(Motor,  port3,          LF_DRIVE,      tmotorVex393_MC29,    openLoop)
#pragma config(Motor,  port4,          L_MANIPULATOR, tmotorVex393_MC29,    openLoop)
#pragma config(Motor,  port5,          R_MANIPULATOR, tmotorVex393_MC29,    openLoop)
#pragma config(Motor,  port6,          L_CORE_LIFT,   tmotorVex393_MC29,    openLoop)
#pragma config(Motor,  port7,          R_CORE_LIFT,   tmotorVex393_MC29,    openLoop)
#pragma config(Motor,  port8,          FLIP_LIFT,     tmotorVex393_MC29,    openLoop)
#pragma config(Motor,  port9,          RF_DRIVE,      tmotorVex393_MC29,    openLoop)
#pragma config(Motor,  port10,         RB_DRIVE,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

// libs
#include "Vex_Competition_Includes.c"
#include "./lib/SmartMotorLib.c"

// forward declaration
typedef struct Drive;
typedef struct Lift;
typedef struct Manipulator;
typedef struct Robot;

Robot robot;


// external file includes
#include "./prototype/joystick_defines.c"
#include "./prototype/drive.c"
#include "./prototype/lift.c"
#include "./prototype/manipulator.c"
#include "./prototype/robot.c"
#include "./prototype/operatorControl.c"



void pre_auton() {
  // smart motor application
  // TODO: cut down smartmotorlib bulk. disallow 292, etc.
  SmartMotorsInit();
  SmartMotorRun();

  // initilize internal variables
  driveInit(&robot.drive);
  liftInit(&robot.lift);
  maniplulatorInit(&robot.manipulator);


  bStopTasksBetweenModes = true;
}

task autonomous() {


  AutonomousCodePlaceholderForTesting();
}


task usercontrol() {
  startTask(taskOPCdrive);
  startTask(taskOPCmanipulate);
  startTask(taskOPClift);

  while (true) {



    wait1Msec(WAIT_TIME);
  }
}
